### ISSUE TITLE
this really needs a simple instalation guide.

### ISSUE THREAD

**Issue by flyon** [jasny/sso#10]
I would really like to use this!
But I need a few words on how to install and test it all.
the demo's are offline, so I really don't know where to start now

**Comment by yekz** [comment]
Although in the end I don't use this to implement my SSO system, but your work really help me to think and learn about it. So just say thanks to you and I will share my code after finish it

**Comment by jasny** [comment]
Let's moved the detailed article out of the README.md file and into the wiki. The README should be focussed on installing and using the library.

**Comment by sankardabest** [comment]
Is same broker ID and broker secret can user for multiple subdomain connection?

**Comment by sankardabest** [comment]
if user login/connected to one subdomain and again if, he go to other subdomain of same server wilh he login to other subdomain automatically with same broker details or anything else?

**Comment by sankardabest** [comment]
Are different brocker id generate on every login or connect request?
