### ISSUE TITLE
i copy one code from version0.23 to 0.3 then it works.

### ISSUE THREAD

**Issue by orchie** [jasny/sso#100]
i used this from an other project, it used version 0.23
i used  composer to require the newest ,3.0 version.
but it dosnt work.
the error is  "Broker didn't send a session key"
i had find other's issues and your reply like https://github.com/legalthings/sso/issues/68#issuecomment-291568629
i know the reason but i dont know how does it works.
then i copied the code where in sso/src/Broker.php function getRequestUrl
`$params['sso_session'] = $this->getSessionId();`
then it works because the broker send a session key by $params['sso_session'] 
is this a bug and why remove it in new version ?

**Comment by jasny** [comment]
Closing all v0.3 related issues. Please update to v0.4.
