### ISSUE TITLE
How to implement SSOServer using database?

### ISSUE THREAD

**Issue by ZulfikarAkbar** [jasny/sso#118]
Hi, thank u for the code in server side , but i dont understand when I change static variable array to database using multidimension assoc array in PHP. Can u help me please?

this my development code:

[server.zip](https://github.com/jasny/sso/files/3958228/server.zip)

**Comment by jasny** [comment]
You need to implement [`getUserInfo()`](https://github.com/jasny/sso/blob/master/examples/server/MySSOServer.php#L81) to load data from the database. The exact implementation of that is outside the scope of this lib.
