### ISSUE TITLE
Can this application use for cross domain single sign on?

### ISSUE THREAD

**Issue by sayakan** [jasny/sso#121]
Hi,

Thank you for developing this application!

I am trying to develop cross domain single sign on application.

Thanks,

**Comment by sayakan** [comment]
I tried this app on AWS EC2.

I made 3 instances and installed this app. Then, I used below command on each server.

```
php -S localhost:9000 -t examples/server/
export SSO_SERVER=http://localhost:9000 SSO_BROKER_ID=Alice SSO_BROKER_SECRET=8iwzik1bwd; php -S localhost:9001 -t examples/broker/
export SSO_SERVER=http://localhost:9000 SSO_BROKER_ID=Greg SSO_BROKER_SECRET=7pypoox2pc; php -S localhost:9002 -t examples/broker/
export SSO_SERVER=http://localhost:9000 SSO_BROKER_ID=Julias SSO_BROKER_SECRET=ceda63kmhp; php -S localhost:9003 -t examples/ajax-broker/
```

It worked!
I am not sure it is same as cross domain environments. because it is in same VPC and same account.
if you have any advice for cross domain single sign on, it would be very helpful! 

Thank you,

**Comment by jasny** [comment]
Yes
