### ISSUE TITLE
How to debug for session id

### ISSUE THREAD

**Issue by sayakan** [jasny/sso#122]
Hello, Thank you for developing this great app.

<img width="300" alt="コメント 2020-07-20 132506" src="https://user-images.githubusercontent.com/51157145/87899539-7d9e9b00-ca8c-11ea-80d0-d8c3eecd808b.png">

When I try to output using `var_dump($variable)`, it is always showed "login failed" on login page as below.

<img width="469" alt="コメント 2020-07-20 135822" src="https://user-images.githubusercontent.com/51157145/87901111-218a4580-ca91-11ea-872d-c4a16ab2fa23.png">

How should I debug for this app? if you have any ideas, please help me. Thank you.

**Comment by jasny** [comment]
Never debug to output. Preferably use [xdebug](https://xdebug.com). Alternatively log to the error log / stderr directly or via monolog.

**Comment by sayakan** [comment]
Thank you!
