### ISSUE TITLE
The broker session id isn't attached to a user session，how to solve this problem?

### ISSUE THREAD

**Issue by xiaojia2017** [jasny/sso#123]
The broker session id isn't attached to a user session，In the network to find a lot of information, but did not find the corresponding solution to this problem, what is the reason for this, do you know how to solve this problem? thank you

**Comment by jasny** [comment]
Check the cache to find the link between the user session and broker token.

**Comment by jasny** [comment]
Closing all v0.3 related issues. Please update to v0.4.
