### ISSUE TITLE
【Single Sign-On Ajax demo】attach sso api return

### ISSUE THREAD

**Issue by showmarker** [jasny/sso#128]
The response header when requesting SSO's Attach interface was alerted and the login status could not be synchronized.
<img width="1265" alt="WechatIMG341" src="https://user-images.githubusercontent.com/74957003/100070830-58280080-2e75-11eb-899c-147c7adac4b6.png">

The warning message is as follows:

_this set-cookie didn`t specify a "SameSite" attribute and was default to "SameSite=Lax" and broke the same rules specified in the SameSiteLax value。_

For example, there are several sites:
- a.com (ajax)
- b.com
- sso.com

When b.com has been successfully logged in, a.com cannot get the login user information.

**Comment by madsnow** [comment]
This can be fixed with you sso-server code

`session_set_cookie_params([
            'secure' => true,
            'path' => '/',
            'samesite' => 'None'
]);`
