### ISSUE TITLE
Use cache library to link sessions

### ISSUE THREAD

**Issue by jasny** [jasny/sso#13]
Remove the option to use symlinks to link sessions. Instead use the [desarrolla2/cache](https://github.com/desarrolla2/Cache) library to store the session id for the broker (replacing [SSO\Session line 157 to 169](https://github.com/jasny/sso/blob/8a1286896f622935f9421538ef568b5d5097dc7e/src/Server.php#L157).

Add a protected function `createCacheAdapter()`, which is called in the constructor. By default the function will create a file cache adapter, using /tmp/sso-sessions as directory. This function can be overloaded when extending the SSO\Server class.

**Comment by jasny** [comment]
No that the whole garbage collection is no longer needed, as it's solved by the caching lib.

**Comment by infabo** [comment]
Not. The caching lib does not implement a GC. Setup a cronjob to delete the old session-files from cache folder, as without the cronjob, it would pollute the filesystem with million of files in a few months.
