### ISSUE TITLE
Is it possible to provide examples of how to use in the framework

### ISSUE THREAD

**Issue by clyde-cn** [jasny/sso#130]
Is it possible to provide examples of how to use in the framework

**Comment by jasny** [comment]
In which framework?

**Comment by clyde-cn** [comment]
CodeIgniter 4   v0.4 ajax login I can not run through

**Comment by clyde-cn** [comment]
v0.3 ajax login attach is the implementation of requesting sso system or requesting the current login system

**Comment by jasny** [comment]
Sorry, I'm not that familiar with CodeIgniter. Please try it yourself and ask a question on StackOverflow if you get stuck.

I strongly recommend upgrading to v0.4. There's a serious security issue in v0.3.

**Comment by clyde-cn** [comment]
ok i will try
