### ISSUE TITLE
Demo not working in Chrome 88.0.4324.146

### ISSUE THREAD

**Issue by dpacassi** [jasny/sso#131]
First off, thanks for this project! I'm currently evaluating if I can use it on a project of mine.
The SSO works in Firefox but doesn't work in Chrome. Not sure why that is as the tricky parts are in the backend (PHP) which should be for all browsers the same.

The login in general works in Chrome, but it only logs you in to the current domain.

My setup:
- macOS Big Sur (11.2)
- Tested in Chrome 88.0.4324.146 (not working)
- Tested in Firefox 85.0.1 (working)
- No web extensions installed, no error messages in the frontend or backend which would explain why it's not working.

How to reproduce:
- git clone git@github.com:jasny/sso.git
- Start servers and brokers as described in the README.md file
- Login to the brokers with one of the defined users

Can you reproduce this bug? Any hints on how to fix it?
Thanks!

**Comment by valtonia** [comment]
I'm also seeing this same issue.

* macOS 11.2
* Chrome 88.0.4324.192 (not working)
* Firefox 85.0.2 (working)
* SSO running on Ubuntu 20.04 + PHP 7.4, using the built in PHP web server

**Comment by MrSwiss** [comment]
I'm having the same issue I found the commit that cause problems 16a4cf1c2784d69f39874a0eb28a297ecba4f188

**Comment by MrSwiss** [comment]
I had found cause of problems it due to recent Chrome update cookie policy https://blog.chromium.org/2019/10/developers-get-ready-for-new.html

my recent commit should fix the problems.

For this to work you need HTTPS connection to your website.

**Comment by jasny** [comment]
Should be fixed with PR.
@dpacassi @valtonia Could you please check and confirm?

**Comment by dpacassi** [comment]
Sorry for the late reply! I can confirm that #132 fixed the issue.
