### ISSUE TITLE
v0.4 How to handle multiple redirects

### ISSUE THREAD

**Issue by clyde-cn** [jasny/sso#133]
How to handle multiple redirects

**Comment by clyde-cn** [comment]
![微信截图_20210415151027](https://user-images.githubusercontent.com/33918985/114829057-349e2c00-9dfd-11eb-96d5-08066e35df48.png)

**Comment by clyde-cn** [comment]
I get multiple domain redirect errors when I jump from a domain t.xx1.my.com to t.xx2.my.com, if I open t.xx2.my.com directly there is no error, I find that when I jump from one of the sites the Referer in the header is different from the current host

**Comment by clyde-cn** [comment]
this class 
![微信截图_20210415152740](https://user-images.githubusercontent.com/33918985/114830933-5dbfbc00-9dff-11eb-9787-06f489e2ffc9.png)

**Comment by rauwebieten** [comment]
I'm having the same issue.

When I click in the browser from broker1 to broker2, and then PHP from broker 2 redirects to the SSO-server.
My Referer header in the SSO-server is then "broker1" and not "broker2" as expected. 

This triggers the BrokerException("Domain of $type is not allowed", 400); on the SSO-server
