### ISSUE TITLE
Storage Access API Support

### ISSUE THREAD

**Issue by esmultivac** [jasny/sso#138]
Hello,

This is a great library, specially because it's a library that everybody can integrate and not a complete solution that may or may not be the correct one for a project. Thanks for that.

The problem is the restrictions of third-party cookies. That affects all SSO solutions, not just this library. Storage Access API seems to be the key to bypass the restrictions, and it's currently supported on Safari, Firefox and Edge. Have you think of updating the library adding support for it. Maybe the library itself doesn't need to change, but the examples surely do.

Thanks,

**Comment by jasny** [comment]
@esmultivac I'm not sure third-party cookie restrictions affect this library. Could you test out the demo using different browsers and see if there are any issues?
