### ISSUE TITLE
Multiple redirects, results in wrong referer validation

### ISSUE THREAD

**Issue by rauwebieten** [jasny/sso#139]
I have a setup with 2 brokers and a server.

When I click in the browser from broker1 to broker2.
And then PHP (from broker2) redirects to the SSO-server.
My Referer header in the SSO-server is then "broker1" and not the expected "broker2".

This triggers the BrokerException("Domain of $type is not allowed", 400); on the SSO-server
Because the SSO server detects the wrong broker.

After some googling, I found this, which confirms my problems:
https://stackoverflow.com/questions/2158283/will-a-302-redirect-maintain-the-referer-string
It seems somewhat browser dependant, but most browsers keep the first referer header.

**Comment by rauwebieten** [comment]
I temporarily got around this issue by setting a header on my brokers:

    Referrer-Policy: same-origin

This omits sending the referer header when doing cross-origin request, which then skips the referer validation on the sso-server.

**Comment by bowvernon110391** [comment]
how do you set it? afaik it needs to be set for each broker's request?

**Comment by rauwebieten** [comment]
> 

Yes, correct. Not a ideal solution, but it fixes the redirects.
