### ISSUE TITLE
Wrong implementation of setcookie

### ISSUE THREAD

**Issue by rauwebieten** [jasny/sso#140]
The signature of setcookie is not correctly used in Broker/Cookies.php line 48 and 62

    $success = setcookie($name, $value, time() + $this->ttl, $this->domain, $this->path, $this->secure, true);

Should be (path and domain changed)

    $success = setcookie($name, $value, time() + $this->ttl, $this->path, $this->domain, $this->secure, true);

**Comment by jasny** [comment]
This was fixed on master, but no new version was released since. I've released v0.4.1
