### ISSUE TITLE
Need compability with laravel 9 

### ISSUE THREAD

**Issue by aldinokemal** [jasny/sso#142]
jasny/sso v0.4.1 requires psr/simple-cache ^1.0 -> found psr/simple-cache[1.0.0, 1.0.1] but the package is fixed to 3.0.0 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.

**Comment by aldinokemal** [comment]
I think you can update psr/simple-cache as well

**Comment by aldinokemal** [comment]
@jasny For newest laravel compatibility we need to upgrade psr/simple-cache version become *

**Comment by jasny** [comment]
@aldinokemal Please create a PR
