### ISSUE TITLE
Session is already started or Session ID cannot be changed when a session is active

### ISSUE THREAD

**Issue by jlslew** [jasny/sso#143]
Hello,

I'm trying to implement SSO using Symfony 6.1 on PHP 8.1 and I'm stuck at [`Server.php:88`](https://github.com/jasny/sso/blob/master/src/Server/Server.php#L88) with 'Session is already started'.  Commenting the exception, I'm then stuck at [`GlobalSession.php:61`](https://github.com/jasny/sso/blob/master/src/Server/GlobalSession.php#L61) with 'Session ID cannot be changed when a session is active'.  Suppressing the warning, I get 'Ignoring session_start() because a session is already active' at the next line.

However, setting a new Session handler class doesn't seem to work or maybe I'm doing something wrong because exception is still thrown.
```php
$this->withSession(new class extends GlobalSession {
    public function isActive(): bool
    {
        return false;
    }
});
```

Furthermore, phpunit is not happy about the following notices:
```
Unsilenced deprecation notices (3)

  1x: Return type of Jasny\SSO\Broker\Cookies::offsetExists($name) should either be compatible with ArrayAccess::offsetExists(mixed $offset): bool, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice
    1x in DashboardControllerTest::testIndex from App\Tests\Controller\Admin

  1x: Return type of Jasny\SSO\Broker\Cookies::offsetGet($name) should either be compatible with ArrayAccess::offsetGet(mixed $offset): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice
    1x in DashboardControllerTest::testIndex from App\Tests\Controller\Admin

  1x: Return type of Jasny\SSO\Broker\Cookies::offsetSet($name, $value) should either be compatible with ArrayAccess::offsetSet(mixed $offset, mixed $value): void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice
    1x in DashboardControllerTest::testIndex from App\Tests\Controller\Admin
```

**Comment by jasny** [comment]
The SSO works by setting the session ID. This doesn’t work if the session is already started.

There's no point changing the code in this library. Instead, you need to make sure that Symfomy doesn't start the session.

You can use a custom session handler. But then still, the session can't be started prior to the SSO lib setting the id.
