### ISSUE TITLE
error ArrayAccess

### ISSUE THREAD

**Issue by asnanmtakim** [jasny/sso#144]
During inheritance of ArrayAccess: Uncaught ErrorException: Return type of Jasny\SSO\Broker\Cookies::offsetExists($name) should either be compatible with ArrayAccess::offsetExists(mixed $offset): bool, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /var/www/html/sso-umsby/sso-pakar/vendor/jasny/sso/src/Broker/Cookies.php:79

**Comment by jasny** [comment]
Likely an incompatibility issue with the latest php version.

**Comment by aldinokemal** [comment]
@jasny do you have any plane to maintenance and upgrade this code?

**Comment by jasny** [comment]
I accept pull requests.
