### ISSUE TITLE
Session cookie on SSO server lost

### ISSUE THREAD

**Issue by esyon** [jasny/sso#145]
Hey there, I got a question regarding session/session lifetime.

The Session Cookie of the SSO-Server lives as long as the session (Browser is opened).
![image](https://user-images.githubusercontent.com/35834723/210228164-12224009-074a-4e37-ac8a-192691e05bcf.png)

If service A attaches to the SSO, logged in, and after that, the Browser gets closed, the Session Cookie on the SSO-Server gets dropped.
After opening the Browser again, Service A is still fine and logged in, as the SSO-tokens are saved via cookies which are still valid:
![image](https://user-images.githubusercontent.com/35834723/210228293-d6dc2213-f369-4bc6-b63a-3e360fa51a73.png)

If I am now opening Service B, which is also connected to the SSO, it is attached to an entirely new Session on the SSO-Server.
Service A is logged in, and Service B is not.

Steps to reproduce:

- go to Service A
- login
- close all browser instances
- reopen Browser
- check on Service A -> still logged in
- open Service B -> logged out

How is this supposed to work? @jasny 

Best regards.

**Comment by jasny** [comment]
The cookie must not outlive the session. So if you set the session to expire when the browser is closed, you must do the same for the cookie.
