### ISSUE TITLE
I got "Expected application/json response, got text/html" when logout.

### ISSUE THREAD

**Issue by MrSwiss** [jasny/sso#42]
When I click logout I got "Expected application/json response, got text/html"
![Error1](http://i.imgur.com/LNk5Q4H.png)

So I try to capture data from (Broker->Server) and I got this(HTTP Error 411).
![Error2](http://i.imgur.com/4C2cXvh.png)

I try to fix this Error by edit[(sso/src/Broker.php) line 254] (https://github.com/jasny/sso/blob/master/src/Broker.php#L254)
I change
`    public function logout()
    {
        $this->request('POST', 'logout');
    }`
to
`    public function logout()
    {
        $this->request('GET', 'logout');
    }`
![Error3](http://i.imgur.com/kPLF4Hv.png)

And, it works fine for me.

I want to know that my hotfix will affect my website security or not? Since, I don't know what I'm doing.

Sorry for my poor English.

**Comment by jasny** [comment]
The hotfix is wrong from a REST point of view. However it won't cause security (or other kind of) issues, since no data is send when logging out.

Typically your webserver should calculate the content length for you. So it looks like a misconfiguration in IIS.
