### ISSUE TITLE
Q: How to implement "remember me" option

### ISSUE THREAD

**Issue by infabo** [jasny/sso#45]
Is there a simple way to implement a "remember me" functionality like known from other sites like Paypal, Facebook, etc.? ("This is a private computer. Keep me logged in until i nuke my browser")

**Comment by infabo** [comment]
Hard ignore?

**Comment by jasny** [comment]
The same way you would normally do. Either don't delete the session, or store an encrypted version of the password in a cookie.

If you have a specific problem with your implementation, please ask a question on [Stackoverflow](http://www.stackoverflow.com).
