### ISSUE TITLE
Any Help implementing it with Laravel 4 or 5

### ISSUE THREAD

**Issue by corientdev** [jasny/sso#50]
Hi,

First of the congrats and thanks for this wonderful library

Please do favour and help me implementing it with laravel.

I think only big problem i could get is with merging the vendor folder because what you used is already used in Laravel.

Kindly Help. Thanks!

**Comment by jasny** [comment]
I don't have to much experience with Laravel, so I can't help you with that. Do note that you should use it as a library, with `$this->server = new SsoServer()`, rather than making it act as a controller.

It's best to [ask a question on StackOverflow](http://www.stackoverflow.com).

**Comment by molerat619** [comment]
@corientdev did you get it to work?

**Comment by bvbilsen** [comment]
Hi all,

I've been developing a package for both a server instance as a client instance. Hopeing to release it anytime soon. It's based upon Jasny's SSO.

**Comment by vishalv26** [comment]
@bvbilsen  thats awesome!
Where can we get it?

**Comment by bvbilsen** [comment]
It's more the question of when...
Hope to publish it in the next few weeks.

**Comment by liuyong888** [comment]
> Hi all,
> 
> I've been developing a package for both a server instance as a client instance. Hoping to release it anytime soon. It's based upon Jasny's SSO.

Hi, has it been posted yet  
TNX
