### ISSUE TITLE
Expected application/json response, got text/html error

### ISSUE THREAD

**Issue by petitbx** [jasny/sso#51]
Hello, 

When I try the examples on my virtual machine I have no problem and that's works fine but when I put it into a web server, I have this error every time Expected application/json response, got text/html

Do you know why I have this error ? 

Thank's a lot, 

PetitBX

**Comment by PanWangJ** [comment]
@petitbx Got the same type of error, if you figure out how to solve this, please share.

**Comment by petitbx** [comment]
@PanWangJ For me, I think the problem is with the web server may be miss something on the web server like a dependency of PHP...

**Comment by PanWangJ** [comment]
@petitbx The problem should be that the server is sending response with content-type set to "text/html" rather than the expected "application/json". The only thing that matters is that I don't know how to solve this problem as I am new to both PHP and SSO.

**Comment by petitbx** [comment]
@PanWangJ Your web server is installed with the extension json.so

**Comment by PanWangJ** [comment]
@petitbx Not sure what json.so is, I just cloned the project into my computer and run the examples.

**Comment by petitbx** [comment]
I solved the problem, just add curl_setopt($ch, CURLOPT_FOLLOWLOCATION, true); line 199 on src/Broker.php

**Comment by jasny** [comment]
The SSO Server will always send a JSON response and never HTML. If the broker received HTML something went wrong. There is either an error and you have `display_errors` enabled (you should log the errors instead), or Apache is giving a response and PHP is never invoked.

@petitbx Using a redirect that isn't followed, is indeed one of the cases when this could occur. Good find.

**Comment by axlyody** [comment]
I've the same problem with this, on my localhost is fine but not from web server. I'm using Plesk, tried to switching php version but nothing happens, even to put into broker.php as @petitbx said. But for php 7.0 i got this error "Broker didn't send a session key". I'm stuck on this
Thx
![](http://i.imgur.com/lHuQSdv.png)

![](http://i.imgur.com/UvRib30.png)
