### ISSUE TITLE
Deployment process 

### ISSUE THREAD

**Issue by sjpatel** [jasny/sso#54]
Hello,
Can you please tell me what is the procedure to deploy this in an aws configuration?
I have tried to run the command php -S SERVER_IP:9000 -t sso/server and then when i try to open my site then its just loading and loading... is there any step that is left while deployment??

There is no much data available for its deployment although ive tested the whole mechanism in my local machine but its not working in live as it does in local. I have double checked all the confguration at deployment.
Iam a bit confused that do i need to run the above stated command or should a virtual host pointed to above directory and host must do the stuff?

**Comment by jasny** [comment]
No that the issue tracker is only for bugs and feature requests. Please ask questions on [StackOverflow](http://www.stackoverflow.com).

The 'Examples' section is just to try it out on your local machine. On AWS you simply serve the pages using Apache. The server an each broker should be on a separate EC2 instance (or external server).
