### ISSUE TITLE
Userinfo method on SSO\Server.php is null

### ISSUE THREAD

**Issue by catcoderphp** [jasny/sso#63]
I try to make login from a broker to the server, but always the server return userinfo method like null, this problem prints on broker: Expected application/json response, got text/html

![image](https://cloud.githubusercontent.com/assets/13856802/23844047/63c9b49e-0785-11e7-933f-eccaf38317fb.png)

I try delete all cookies and all sessions but the problem is not fixed

![image](https://cloud.githubusercontent.com/assets/13856802/23844212/654ed1ea-0786-11e7-8581-16298d5742c8.png)

**Comment by jasny** [comment]
@catcoderphp Your not receiving a JSON response. This typically has one of two reasons

* The request isn't handled by the SSO server at all
* The SSO server has a fatal error and `display_errors` is enabled

Set a breakpoint to check the `$response` in [Broker.php on line 205](https://github.com/jasny/sso/blob/master/src/Broker.php#L205).
_(Alt, use `var_dump` if you're [not enlightened yet](https://www.sitepoint.com/debugging-and-profiling-php-with-xdebug/) :stuck_out_tongue:)_
