### ISSUE TITLE
Broker didn't send a session key

### ISSUE THREAD

**Issue by mcmf** [jasny/sso#64]
getRequestUrl  not set the $params['sso_session'] = $this->getSessionId();  

  $sid = $this->getBrokerSessionID();  no session

**Comment by mcmf** [comment]
or  like this ? 

protected function getBrokerSessionID()
        {
            $headers = getallheaders();

            if (isset($headers['Authorization']) &&  strpos($headers['Authorization'], 'Bearer') === 0) {
                $headers['Authorization'] = substr($headers['Authorization'], 7);
                return $headers['Authorization'];
            }
            if (isset($_GET['access_token'])) {
                return $_GET['access_token'];
            }
            if (isset($_POST['access_token'])) {
                return $_POST['access_token'];
            }
            if (isset($_GET['sso_session'])) {
                return $_GET['sso_session'];
            }
            if ($this->getSessionId()){
                return $this->getSessionId();
            }
            return false;
        }

**Comment by jasny** [comment]
Debug to find out why.
