### ISSUE TITLE
Joomla - Broker didn't send a session key

### ISSUE THREAD

**Issue by tw88** [jasny/sso#68]
Hi,

im using your lib to integrate it into an old Joomla site.

It fails with "Broker didn't send a session key", any Idea what causes this or how to fix it?

**Comment by jasny** [comment]
The broker did a request to the server without passing the sso session. It needs to send one of the following:

* An `Authorization` header that starts with `Bearer `, followed by the session id
* An `access_token` query parameter (`$_GET`) with the session id
* An `access_token` post parameter (`$_POST`) with the session id
* An `sso_session` query parameter _(deprecated)_

See https://github.com/jasny/sso/blob/master/src/Server.php#L97

**Comment by tw88** [comment]
So i logged everything to understand whats happening on our broker and server - the issue was our server had a slightly older version of the lib and so it did not look for the Authorization Header. 

Maybe you should add a Version check to the communication between server and broker to notice if they are not compatible.

Thanks for the quick response btw.
