### ISSUE TITLE
Is it stable/mature enough to be used in prod?

### ISSUE THREAD

**Issue by cocochepeau** [jasny/sso#73]
Hello,

First of all, thank you for this amazing package.
As said in the title, I might be using it in prod environment. Is it stable/mature enough?

Regards,

**Comment by jasny** [comment]
@cocochepeau We're using it in production. So yes, to some extend. However...

It's not very mature, yet. I want to improve the code quality quite a bit. It also isn't stable yet, as there the code needs to become more mature and BC breaks are required to do so. Also in terms of security, a lot of improvements need to be made.

If stability and maturity is very important to you, maybe skip this lib for now. Instead rely on CAS.
