### ISSUE TITLE
Use interface to store session data

### ISSUE THREAD

**Issue by Veitor** [jasny/sso#76]
I found now session is strored in `$_SESSION` 

maybe set session store place configurable is better, such as use redis,memcache

**Comment by tangzhangming** [comment]
In the third party package Jasny \ SSO \ Server file can be set memcache other ways
use Desarrolla2 \ Cache \ Cache;
use Desarrolla2 \ Cache \ Adapter;

Refer to https://github.com/desarrolla2/Cache

**Comment by jasny** [comment]
Fixed in v0.4
