### ISSUE TITLE
everyday log out 

### ISSUE THREAD

**Issue by pramodwerea** [jasny/sso#78]
Hi, I started using this SSO and almost every things seem fine. The only thing I notice every day when I visit my site I need to log in (logged out from all sites). Is there any session inactive duration that is killing/expiring the session so that every day I need to do log in? I have set cookies lifetime for 1 week.

**Comment by jasny** [comment]
There is the cookie lifetime, but also the session clean up. Make sure you've set `gc_maxlifetime` to more than a week (like 8 days). https://blogs.oracle.com/oswald/php:-sessiongcmaxlifetime-vs-sessioncookielifetime

**Comment by infabo** [comment]
1 day - already 21 hours longer than in my case. I set the timeout to 24h, but losing session every ~1,5 hours (didn't time it).
Already preparing popcorn, can't await jasny's argumentation on closing this issue. hoho

**Comment by munvier** [comment]
I had the same trouble, be sure to inspect the cookie "sso_token_xxx" and see what expires it has. I thought everything was fine in server conf but I saw that the cookie was only 1h...

**Comment by munvier** [comment]
I made a recent pull request because the cookie was set to one hour in the code. Now you can pass a parameter in the Broker construction that will set this duration.

`$broker = new Broker(getenv('SSO_SERVER'), getenv('SSO_BROKER_ID'), getenv('SSO_BROKER_SECRET'), 86400);`

**Comment by infabo** [comment]
cookie already at 86400 and session.gc_maxlifetime = 86400 too.
But still it loses session after 1-2 hours.

**Comment by jasny** [comment]
@infabo Make sure that the session file still exists. In some environments (Ubuntu / Debian) there is a cron job that deletes the session files, rather than that `gc_maxlifetime` is used.

**Comment by infabo** [comment]
wow. this was new to me.
So gc_maxlifetime as a PHP ini_set or .htaccess php_value approach is totally overruled by this stupid cronjob.

**Comment by pramodwerea** [comment]
@infabo, have you managed to resolve your issue with logout? Because still I have the same problem. My sessions are stored in dynamo DB outside and for caching I am using memcached.

**Comment by DonaldoLog** [comment]
@infabo, hello I have that issue,  the session finish after 1-2 hours. Some idea to resolve this issue?
I use file session.

**Comment by infabo** [comment]
If you are in Ubuntu, there is a cronjob which cleans up orphan php sessions on a regular basis. Have a look at the files in /etc/cron.d/
