### ISSUE TITLE
Please check for existence of ? in URL before appending params

### ISSUE THREAD

**Issue by kwentworth** [jasny/sso#81]
I have query params in my return_url already.  Can you change your code to look for a ? and use an & accordingly?

Something like this:
`$char = strpos($loginAction, '?') === false ? '?' : '&';`

Could be used on:

Server.php, line 40:
`$url = $_REQUEST['return_url'] . $char.'sso_error=' . $message;`

Broker.php, line 137:
` return $this->url . $char . http_build_query($data + $params);`

Broker, line 174:
`return $this->url . $char . http_build_query($params);`

**Comment by jasny** [comment]
Fixed in v0.4
