### ISSUE TITLE
Redirect back to client (broker) self after login.

### ISSUE THREAD

**Issue by kelvinhalim13** [jasny/sso#82]
First of all i would to said thank you for giving this SSO.

As mention in example the login page is coming from each client and not from the server. I have do some experience on the login page which it is using server login page. So that all client using 1 login page.

The problem is. It is possible to redirect to the client url after successful login in server?.

**Comment by kelvinhalim13** [comment]
I found attach function which if it is set to be true or our redirect uri, we will get `$_REQUEST['return_url']` in our server which handle the `command`.

I have try to save the `return_url` manual by set in on `cookie` or` session`. However after reach the login, i try to get my return url cookie or session, it always return null. Any idea how this could be happen and how to handle this?

**Comment by jasny** [comment]
@kelvinhalim13 I don't have enough information to help you. Could you please ask this question on [Stackoverflow](http://stackoverflow.com) and include the necessary code. If needed, ping me on Twitter.
