### ISSUE TITLE
The broker session id isn't attached to a user session

### ISSUE THREAD

**Issue by andersonn-roberto** [jasny/sso#83]
I'm developing some Laravel projects to implement SSO, I've created one server and two clients to check if it works.
But when I try to register a user or even login one, I always receive that error message.
Is there a way to debug and see what is happening?
I guess it could be a problem with the cache, I'm on windows and I don't know where the directory _/tmp_ would be created.
I appreciate any help on this.

Thanks!

**Comment by jasny** [comment]
@andersonn-roberto Please overwrite the method and write to a directory that exists.
