### ISSUE TITLE
was not logged in all sites

### ISSUE THREAD

**Issue by pramodwerea** [jasny/sso#84]
Today I noticed one issue with SSO, after adding one more site that uses SSO.Now I am running three sites with SSO.

CASE1: 

> yesterday I have logged in all three sites and SSO was fine. But today when I browsed the first site I was not logged in and it redirected me to log in a page and I did log in. After logged in I visited another site and there I was not logged in. Then I tried the third site, there also I was not logged in.

CASE2: 

> continuing the case 1: then I tried to log in the second site and then I was also logged in third one. When I tried to log out from the first site, it did not log out me from the other 2 sites.

CASE3:

> when I removed the cookies from the first site and tried log in, then everything was fine (SSO was synching).

Could you please help to understand where could be the problem? What could be the possible solution?

**Comment by pramodwerea** [comment]
any feedback/suggestions would be appreciated!

**Comment by jasny** [comment]
Make sure the sure the TTL of session cookie of the server is lower than that of the brokers. In fact you might set the TTL of the broker cookies really high (like 10 years from now).
