### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by 4m3x** [jasny/sso#85]
This is a **great** way to achieve SSO and I would really like to implement this...however the install instructions are very vague and confusing..for me at least.
Does anybody have simpler install instructions to get this going ...it should really be as easy as place these files on server SSO,, then place these on website (broker)..then  configure this file and boom.

I am **not** that PHP advanced so i find it really hard to grasp....Also...how would you link the webapp to talk to the server if every webapp is different..? 

Any help or input would be much appreciated!

** EDIT  **
Ok, so I Managed to get them all running on one machine, but I still fail to see how will website 1 know to to use the broker instead of verifying its own credentials...and then after that how does website2 know to use broker?
OR:
Do you run both server and broker on each website you want SSO on?

**Comment by jasny** [comment]
Please ask on stackoverflow.com
