### ISSUE TITLE
Unknow command

### ISSUE THREAD

**Issue by andersonn-roberto** [jasny/sso#86]
This error occurs after you fill the fields: email and password and hit the login button.
The server response with:

```
Exception
Unknown command
--
in Client1Broker.php (line 60)
at Client1Broker->request('POST', 'login-user', array('error' => 'Unknown command'))in Broker.php (line 291)
at Broker->__call('loginUser', array('jackie.black@example.com', 'jackie123'))in LoginController.php (line 47)
```

Anyone know what can be the problem?
Thanks!

**Comment by jasny** [comment]
The SSO server doesn't have the `login-user` command / `loginUser` function.

**Comment by andersonn-roberto** [comment]
So, I need to implement this function?

**Comment by dharmikvyas** [comment]
did you find out to work this example

**Comment by jasny** [comment]
@dharmikvyas I recommend looking at the v0.4 branch instead. I'll release that shortly and subsequently drop support for v0.3.
