### ISSUE TITLE
Mismatched session id

### ISSUE THREAD

**Issue by pyrochlore** [jasny/sso#93]
Hi,
I tried to using the code in my test sites but got errors 'Expected application/json response, got text/html'.
From the code, I found it is caused by the mismatch of current session id (on server) to the cached $linkedId. (Server.php line 84)
Also, I found the session id got in examples/server/index.php is different for requesting from command 'attach' or from command 'login'.
Do you have any idea why this happened?
Thanks.

**Comment by jasny** [comment]
Closing all v0.3 related issues. Please update to v0.4.
