### ISSUE TITLE
Undefined index: error line 224: jasny/sso/src/Broker.php

### ISSUE THREAD

**Issue by tantana5** [jasny/sso#99]
![untitled](https://user-images.githubusercontent.com/19582951/45198188-718e0380-b28f-11e8-9c2a-9d177e3217a2.png)

**Comment by tantana5** [comment]
why don't use Guzzle, man?

**Comment by eleftrik** [comment]
Same error here. Has this project's development been abandoned?

**Comment by saviorlv** [comment]
isset($data['error'])

**Comment by jasny** [comment]
Closing all v0.3 related issues. Please update to v0.4.
